### ISSUE TITLE
Empty repo

### ISSUE THREAD

**Issue by Rezokeun** [bennettapps/Budget-App#3] opened 2019-06-14 01:54 UTC
Add a text file such as hello world or something of that sort to get used to git commits and PRs. We won't worry about PR approvals right now, just focus on getting used to the tool. I also have cloned the repo on my end so I can pull and commit as well to give you a feel for how handling commits from others will feel like.

**Comment by bennettapps** [comment] 2019-06-14 17:31
Is this a duplicate of issue #1 ?

**Comment by Rezokeun** [comment] 2019-06-15 01:33
Yea, you can consider it a duplicate. I just happened to provide more information and guidance into what you should do in this issue. You can close this out as long as you understand what I posted in the initial issue message.

**Closed as completed** 2019-06-19 20:12 UTC
